#server:
#  port: 3000
#
#
#spring:
#  redis:
#    host: 122.51.39.181
#    database: 0
#  main:
#    allow-bean-definition-overriding: true
#    jackson:
#      time-zone: GMT+8
#      date-format: yyyy-MM-dd HH:mm:ss
#    datasource:
#      type: com.zaxxer.hikari.HikariDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://122.51.39.181:3306/ituac?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
#      username: root
#      password: 123456
#      hikari:
#        minimum-idle: 5
#        idle-timeout: 600000
#        maximum-pool-size: 10
#        auto-commit: true
#        pool-name: MyHikariCP
#        max-lifetime: 1800000
#        connection-timeout: 30000
#        connection-test-query: SELECT 1

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:3001/users/current
    client:
      id: client_2
      client-secret: 123456
      access-token-uri: http://localhost:3001/oauth/token
      grant-type: client_credentials,password
      scope: server