spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        # 认证中心
        - id: ituac-cloud-auth
          uri: lb://ituac-cloud-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - ValidateCodeGatewayFilter
            # 前端密码解密
            - PasswordDecoderFilter
        #UPMS 模块
        - id: ituac-upms-admin-server
          uri: lb://ituac-upms-admin-server
          predicates:
            - Path=/admin/**
          filters:
            # 限流配置
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200


security:
  encode:
    # 前端密码密钥，必须16位
    key: 'thanks,ituacCloud'

# 不校验验证码终端
ignore:
  clients:
    - test
