


zuul:
  host:
    #zuul配置
    max-per-route-connections: 50
    max-total-connections: 200
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  #关闭重试机制
  retryable: true
  routes:
    auth:
      #说明: path不是微服务的地址而是自己定义的地址如果微服务地址为 /api/product 则此处访问地址为: /product/api/product
      path: /uaa/**
      sensitiveHeaders:
      serviceId: ituac-cloud-auth
      #strip-prefix: false

  
  include-debug-header: true
  #添加代理头
  add-proxy-headers: true