spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.10.44:3306/spring-cloud-auth2-db?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: dev
    password: NHdev2015
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true